### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by skoch** [klaut/brio#2]
```
$ brio stream
error: undefined method `each' for #<Brio::Resources::NullResource:0x007f9c23d172e0>
===
$ brio stream -g
error: undefined method `each' for #<Brio::Resources::NullResource:0x007fa61d5543d8>
===
$ brio whois

error: undefined method `name' for #<Brio::Resources::NullResource:0x007f8a03596ca0>
```

ruby-2.0.0-p0

**Comment by obstschale** [comment]
I've the same error message.

using: ruby 1.9.3 and openssl ;)

**Comment by klaut** [comment]
I will have a look at it.
I tested it with 2.0.0 1.9.2 and 1.9.3 and it should be working fine... but will try and see what can cause this.

**Comment by klaut** [comment]
@skoch , @obstschale : could you please paste me again the "rvm info" and "gem list"?
I am assuming you are both on macosx, right?

**Comment by obstschale** [comment]
Yes, I'm using MacOSX

```
o rvm info                                                    (Wed, Feb 27)

ruby-1.9.3-p392:

  system:
    uname:       "Darwin RetinaObst.local 12.2.1 Darwin Kernel Version 12.2.1: Thu Oct 18 16:32:48 PDT 2012; root:xnu-2050.20.9~2/RELEASE_X86_64 x86_64"
    system:      "osx/10.8/x86_64"
    bash:        "/usr/local/bin/bash => GNU bash, version 4.2.42(2)-release (i386-apple-darwin12.2.1)"
    zsh:         "/bin/zsh => zsh 4.3.11 (i386-apple-darwin12.0)"

  rvm:
    version:      "rvm 1.18.14 (stable) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "10 hours 52 minutes 37 seconds ago"

  ruby:
    interpreter:  "ruby"
    version:      "1.9.3p392"
    date:         "2013-02-22"
    platform:     "x86_64-darwin12.2.1"
    patchlevel:   "2013-02-22 revision 39386"
    full_version: "ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin12.2.1]"

  homes:
    gem:          "/Users/RetinaObst/.rvm/gems/ruby-1.9.3-p392"
    ruby:         "/Users/RetinaObst/.rvm/rubies/ruby-1.9.3-p392"

  binaries:
    ruby:         "/Users/RetinaObst/.rvm/rubies/ruby-1.9.3-p392/bin/ruby"
    irb:          "/Users/RetinaObst/.rvm/rubies/ruby-1.9.3-p392/bin/irb"
    gem:          "/Users/RetinaObst/.rvm/rubies/ruby-1.9.3-p392/bin/gem"
    rake:         "/Users/RetinaObst/.rvm/gems/ruby-1.9.3-p392/bin/rake"

  environment:
    PATH:         "/Users/RetinaObst/.rvm/gems/ruby-1.9.3-p392/bin:/Users/RetinaObst/.rvm/gems/ruby-1.9.3-p392@global/bin:/Users/RetinaObst/.rvm/rubies/ruby-1.9.3-p392/bin:/Users/RetinaObst/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin"
    GEM_HOME:     "/Users/RetinaObst/.rvm/gems/ruby-1.9.3-p392"
    GEM_PATH:     "/Users/RetinaObst/.rvm/gems/ruby-1.9.3-p392:/Users/RetinaObst/.rvm/gems/ruby-1.9.3-p392@global"
    MY_RUBY_HOME: "/Users/RetinaObst/.rvm/rubies/ruby-1.9.3-p392"
    IRBRC:        "/Users/RetinaObst/.rvm/rubies/ruby-1.9.3-p392/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

```
o gem list                                                    (Wed, Feb 27)

*** LOCAL GEMS ***

addressable (2.3.3)
bigdecimal (1.1.0)
brio (0.0.3)
bundler (1.3.0)
faraday (0.8.6)
faraday_middleware (0.9.0)
gli (2.5.4)
highline (1.6.15)
htmlentities (4.3.1)
io-console (0.3)
json (1.7.7, 1.5.5)
launchy (2.2.0)
minitest (2.5.1)
multipart-post (1.1.5)
rake (10.0.3, 0.9.2.2)
rdoc (3.9.5)
rubygems-bundler (1.1.1)
rvm (1.11.3.6)
```

**Comment by klaut** [comment]
ok, perhaps the .brio.rc file got messed up or the token was not properly saved.

Try this and report if it worked or not:
1) go to your $HOME directory and remove .brio.rc

```
$ cd $HOME
$ rm ~/.brio.rc
```

Then run the authorization again

```
$ brio authorize
```

Now, follow the instructions on the command line (press ENTER to open the webpage in the browser)
Copy the token that is displayed on the webpage:

```
Thank you for authorizing brio

Copy the token below, paste it in your terminal and close this window.

Your token: [[[[ COPY THIS PART HERE ]]]]
```

Now paste this token into the console. Press enter. And you should receive a confirmation that you have been authorized.
Try to run "brio stream" again and let me know if the problem still persist.

Be careful to correctly copy/paste the token, because if not the stream call will not be able to properly authorize and you will get that same error again.

I just tried this and was able to reporduce the error here. Nice catch, guys! :thumbsup:
Will fix this to display proper error messages instead of the ruby default ones

## UPDATE

This will work for ruby 1.9.3
@obstschale you are experiencing this bug because you ran "brio authorize" with ruby 2.0.0. Ruby 2.0.0 stores yaml in a slightly different style now, so i will need to fix this. Definitely a bug. Thanks for reporting it!

**Comment by obstschale** [comment]
Thx @klaut that was the problem :) #brio works now just fine.

**Comment by klaut** [comment]
@skoch you will need to do 2 things to make it work:

1) delete .brio.rc from your $HOME directory

```
$ rm ~/.brio.rc
```

2) update brio gem:

```
$ gem update brio
```

Then you can run authorize again and everything should work.

**Comment by skoch** [comment]
Thanks all, seems to be working fine now. :thumbsup:

**Comment by griffmiester** [comment]
I've know this has been closed, but I'm having the same issue.
When I've tried brio authorize, the webpage it's opening to bass the URL 
https://brioapp.herokuapp.com/auth/callback/#error_description=Non-developer+apps+can+only+be+authorized+by+their+owner.&error=personal_use_only
and there doesn't seem to be an actual token on the page.

**Comment by klaut** [comment]
hi @griffmiester 

this error is happening because i do no longer have a developer account on app.net. so brio does not get authorized properly. I am trying to find somewhere else to host brio oauth page. 

sorry about that :(
